require 'rake/clean'

$base = 'h-w'

CLEAN.include "#$base.aux"
CLEAN.include "#$base.log"
CLOBBER.add "#$base.pdf"

task :default => "#$base.pdf"

file "#$base.pdf" => "#$base.tex" do |t|
  sh "pdflatex #{t.source}"
end
