require 'rake/clean'

$base = 'h-w'

['aux', 'log', 'bbl', 'bcf', 'blg', 'run.xml'].each do |ext|
  CLEAN.include "#$base.#{ext}"
end
CLOBBER.add "#$base.pdf"

task :default => "#$base.pdf"

file "#$base.pdf" => "#$base.tex" do |t|
  sh "pdflatex #{t.source}"
  sh "biber #$base"
  (1..2).each do
    sh "pdflatex #{t.source}"
  end
end
